name: Publish to Blockware Public NPM
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: ${{ secrets.GCP_ARTIFACT_NPM_URL }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_ARTIFACTORY_SERVICE_ACCOUNT }}
          export_default_credentials: true
      - run: npm install
      - run: npm publish
